import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../app/components/footer/page"
import Navbar from "../app/components/navbar/page";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Toaster
          position="top-right"
          toastOptions={{
            duration: 3000,
            success: {
              style: {
                background: "green",
                color: 'white'
              },
            },
            error: {
              style: {
                background: "red",
                color: 'white'
              },
            },
          }}
        />
        <Navbar />
        {children}
      <Footer/>
      </body>
    </html>
  );
}
